import{a as v,S as w,i as l}from"./assets/vendor-ee72e1a4.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();async function m(r=1,t){const s="https://pixabay.com/api/";return(await v.get(s,{params:{page:r,per_page:15,key:"44178222-91171e7a1f266369aa2a731c5",q:t,image_type:"photo",orientation:"horizontal",safesearch:!0}})).data}function f(r){return r.map(({webformatURL:t,largeImageURL:s,tags:i,likes:e,views:o,comments:n,downloads:L})=>`
<li class="gallery-item">
  <a class="img-link" href="${s}">
    <img class="gallery-img" alt="${i}" src=${t}></img> </a>
    <div class="stats-container">
      <span class="stats-info"><h5>Likes:</h5><p>${e}</p></span>
      <span class="stats-info"><h5>Views:</h5><p>${o} </p></span>
      <span class="stats-info"><h5>Comments:</h5><p>${n}</p></span>
      <span class="stats-info"><h5>Downloads:</h5><p>${L}</p></span>
    </div>
</li >
`).join("")}function y(){new w(".gallery a",{captionDelay:"250ms",captionsData:"alt"}).refresh()}const x=document.querySelector(".search-form"),c=document.querySelector(".gallery"),F=document.querySelector(".loader"),g=document.querySelector(".load-btn");function C(){F.style.visibility="visible"}function b(){F.style.display="none"}function M(){g.style.visibility="visible"}function p(){g.style.visibility="hidden"}b();p();x.addEventListener("submit",q);let a=1,S=15,u=null,d=null,h=null;function q(r){r.preventDefault();const t=r.target.elements.search.value.trim();if(!t)return l.show({message:"You can't do that here",position:"topRight",backgroundColor:"#EF4040",messageColor:"#FFFFFF"});if(t.length>100)return l.show({message:"It's too long, buddy",position:"topRight",backgroundColor:"#EF4040",messageColor:"#FFFFFF"});d=t,c.innerHTML="",a=1,p(),C(),m(a,d).then(s=>{s.hits.length!=0?(c.insertAdjacentHTML("beforeend",f(s.hits)),y(),u=Math.ceil(s.totalHits/S),a<u&&M(),h||(h=document.querySelector(".gallery-item").getBoundingClientRect()),r.target.elements.search.value=""):l.show({message:"Sorry, there are no images matching your</br> search query. Please try again!",maxWidth:"432px",position:"topRight",backgroundColor:"#EF4040",messageColor:"#FFFFFF"})}).catch(s=>{console.log(s)}).finally(()=>{b()})}g.addEventListener("click",E);async function E(r){a+=1;try{const t=await m(a,d);c.insertAdjacentHTML("beforeend",f(t.hits)),y(),window.scrollBy({top:h.height*2,left:0,behavior:"smooth"}),a>=u&&(p(),l.show({message:"We're sorry, but you've reached the end of search results.",maxWidth:"432px",position:"topRight",backgroundColor:"#EF4040",messageColor:"#FFFFFF"}))}catch(t){console.log(t.message)}}
//# sourceMappingURL=commonHelpers.js.map
